name: Windows build

on:
  push:
    branches: [ master,testing ]
  pull_request:
    branches: [ master,testing ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'This is test description'
        # Default value if no value is explicitly provided
        default: 'Hello World'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:
    runs-on: windows-2019
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
    - name: setup_system
      shell: cmd
      run: ./build/windows/10_setup_system.cmd
    - name: compile
      shell: cmd
      run: ./build/windows/20_build.cmd
    - name: portable
      shell: cmd
      run: ./build/windows/30_portable.cmd

    - uses: actions/upload-artifact@v2
      with:
        name: xclu-bin
        path: build/windows/Xclu-bin/**/*
    - uses: actions/upload-artifact@v2
      with:
        name: portable
        path: build/windows/xclu-bin-windows-portable.zip
